all:
  children:
    mynginx:
      hosts:
        red:
          ansible_host: "{{ red_ip }}"
          ansible_user: "{{ ansible_user }}"
          ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
        green:
          ansible_host: "{{ green_ip }}"
          ansible_user: "{{ ansible_user }}"
          ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
